version: '3.4'

 

services:
  apigateway:
    container_name : api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 8001:80 
    networks:
      - backend
    environment:
      - DB_HOST=localhost
      - DB_NAME=Tesodev

  tesodev:
    container_name: Tesodev
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend


networks:
  beckend:
    driver: bridge